setup:
  mode: random
  num_nodes: 10
  graph_model: 'watts_strogatz'

model_params:
  k: 4
  p_rewire: 0.1

# Min and max of the random generations
attributes:
  node:
    ram: 'random.uniform(1, 16)'
  
  edge:
    delay: 'random.uniform(0.1, 5.0)'

  infrastructure:
    actions:
      disable_random_node:
        distribution: 'random.uniform(0, 300)'
        action_params: 
          event_set: None
          distribution_to_enable_node: 'random.uniform(0, 100)'
  
  app:
    num_apps: 3
    popularity: [0.1, 1.0]
    cpu: [0.1, 4.0]
    ram: [0.5, 8.0]
    disk: [10, 100]
    time: [0, 300]
    actions: 
      remove_app:
        distribution: 'random.uniform(0, 300)'
        action_params: 
          user_set: None,
          event_set: None
      increase_popularity:
        distribution: 'random.uniform(0, 300)'
        action_params:
          multiplier: 'random.uniform(1, 3)'
          user_set: None,
      decrease_popularity: 
        distribution: 'random.uniform(0, 300)'
        action_params:
          multiplier: 'random.uniform(0, 1)'
          user_set: None,
    
  user:
    num_users: 2
    request_ratio: [0.1, 1.0]
    request_popularity: [0.1, 1.0]
    centrality: [0.1, 1.0]
    actions:
      remove_user:
        distribution: 'random.uniform(0, 300)'
        action_params:
          event_set: None
      move_user:
        distribution: 'random.uniform(0, 300)'
        action_params: 
          infrastructure: None
      increase_request_ratio:
        distribution: 'random.uniform(0, 300)'
        action_params:
          multiplier: 'random.uniform(1, 3)'
      decrease_request_ratio: 
        distribution: 'random.uniform(0, 300)'
        action_params:
          multiplier: 'random.uniform(0, 1)'

  new_object:
    new_user: 
      distribution: 'random.uniform(0, 300)'
      action_params:
        config: None,
        app_set: None,
        user_set: None,
        infrastructure: None,
        event_set: None

    new_app: 
      distribution: 'random.uniform(0, 300)'
      action_params:
        config: None,
        app_set: None,
        user_set: None,
        infrastructure: None,
        event_set: None,
        num_new_users: 'random.randint(1, 5)'
    
    # new_disabled_node: